spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:account_reservation}
    username: ${DATABASE_USER:admin}
    password: ${DATABASE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db-changelog-master.xml

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,metrics,threaddump,loggers,heapdump
  endpoint:
    heapdump:
      access: read-only
    shutdown:
      access: none